services:
  postgres:
    image: 'postgres'
    environment:
      - 'POSTGRES_DB=${POSTGRES_DATABASE:-station_db}'
      - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-very_secret}'
      - 'POSTGRES_USER=${POSTGRES_USER:-station_user}'
    restart: unless-stopped
    volumes:
      - postgres-data2:/var/lib/postgresql/data
    networks:
      - docker-net
    ports:
      - '9042:5432'
  redis:
    image: redis:${REDIS_VERSION:-6.2}-alpine
    restart: unless-stopped
    command: redis-server --requirepass ${REDIS_PASSWORD:-very_secret}
    volumes:
      - redis-data:/data
    networks:
      - docker-net
    ports:
      - "${REDIS_PORT:-6379}:6379"
  minio:
    image: docker.io/bitnami/minio:2022
    ports:
      - '9000'
      - '9001'
    networks:
      - docker-net
    volumes:
      - minio-data:/data
    environment:
      - MINIO_ROOT_USER=${MINIO_USER:-station_user}
      - MINIO_ROOT_PASSWORD=${MINIO_PASSWORD:-very_secret}
      - MINIO_DEFAULT_BUCKETS=${MINIO_BUCKET:-station}

  keycloak:
    image: quay.io/keycloak/keycloak:23.0.7
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/${KEYCLOAK_DATABASE:-station_auth}
      KC_DB_USERNAME: ${POSTGRES_USER:-station_user}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD:-very_secret}

      KC_HOSTNAME: ${KEYCLOAK_HOST:-localhost}
      KC_HOSTNAME_PORT: ${KEYCLOAK_PORT:-9097}
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_LOG_LEVEL: info
      KC_METRICS_ENABLED: true
      KC_HEALTH_ENABLED: true
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN_USER:-admin}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD:-very_secret}
    command: start-dev
    networks:
      - docker-net
    depends_on:
      - postgres
    ports:
      - "${KEYCLOAK_PORT:-9097}:8080"

#  station_backend:
#    build: .
#    depends_on:
#      - postgres
#      - redis
#      - minio
#      - keycloak
#    ports:
#      - "${TOMCAT_PORT:-8080}:${TOMCAT_PORT:-8080}"
#    networks:
#      - docker-net
#    volumes:
#      - ./.env:/app/.env

volumes:
  postgres-data2:
    driver: local
  redis-data:
    driver: local
  minio-data:
    driver: local

networks:
  docker-net:
    external: true