database:
  url: jdbc:postgresql://${POSTGRES_HOST}:5432/${POSTGRES_DATABASE}
  username: ${POSTGRES_USER}
  password: ${POSTGRES_PASSWORD}

server:
  port: ${TOMCAT_PORT}
  tomcat:
    threads:
      max: 600

spring:
  application:
    name: station
    version: 1.0.0
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 12MB
  banner:
    charset: utf-8
    location: static/banner/sepidan-station.txt
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
  datasource:
    url: ${database.url}
    username: ${database.username}
    password: ${database.password}


  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    url: ${database.url}
    user: ${database.username}
    password: ${database.password}

  data:
    redis:
      database: 0
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}

  docker:
    compose:
      file: docker-compose.yml

springdoc:
  swagger-ui:
    path: /api-docs/swagger-ui
  api-docs:
    path: /api-docs/manual