iam:
  url: http://localhost:${KEYCLOAK_PORT}
  realm: station
  issuer: ${iam.url}/realms/${iam.realm}
  client-id: springboot
  client-secret: f3xjGSZaJFBv49kbwbE0aX9UmD5B2kLI
  client-manager-username: springboot-admin
  client-manager-password: very_very_secret

database:
  url: jdbc:postgresql://${POSTGRES_HOST}:5432/${POSTGRES_DATABASE}
  username: ${POSTGRES_USER}
  password: ${POSTGRES_PASSWORD}

server:
  port: ${TOMCAT_PORT}
  tomcat:
    threads:
      max: 600

spring:
  application:
    name: station
    version: 1.0.0
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 12MB
  banner:
    charset: utf-8
    location: static/banner/sepidan-station.txt
  datasource:
    url: ${database.url}
    username: ${database.username}
    password: ${database.password}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${iam.issuer}

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    url: ${database.url}
    user: ${database.username}
    password: ${database.password}

  data:
    redis:
      database: 0
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}

  docker:
    compose:
      file: docker-compose.yml

  devtools:
    add-properties: true
    restart:
      enabled: true
    livereload:
      enabled: true

springdoc:
  swagger-ui:
    path: /api-docs/swagger-ui
  api-docs:
    path: /api-docs/manual

logging:
  level:
    web: debug
    liquibase: debug
    feign: debug